### ISSUE TITLE
Document SoccerMon dataset

### ISSUE THREAD

**Issue by cise-midoglu** [simulamet-host/soccer-dashboard#14]
https://docs.google.com/spreadsheets/d/1obPsoOCSkwAvjw6bxGhX3AmwGqKOwnR42-YF2HJCJ_o/edit?usp=sharing

**Comment by cise-midoglu** [comment]
You can also add notes about where, i.e., in which file(s), each category of parameters can be found.

**Comment by cise-midoglu** [comment]
Check out the literature as well: https://drive.google.com/drive/folders/1hOw_Xg_lFrjlAbTZR84A3thteH7PRTAr?usp=sharing

**Comment by cise-midoglu** [comment]
SoccerMon dataset: https://osf.io/uryz9/

**Comment by cise-midoglu** [comment]
- [x] @mmainulhasan : subjective metrics
- [x] @Hens743 : objective metrics

**Comment by mainulspace** [comment]
I have filled up the cells I found from the literature and data set. Please review.

**Comment by cise-midoglu** [comment]
Related issue: https://github.com/simulamet-host/pmsys-db/issues/19

Resources: 
(http://home.simula.no/~paalh/students/)
- https://home.simula.no/~paalh/students/SiarheiKulakou.pdf
- https://home.simula.no/~paalh/students/NourhanRagab-OsloMet-2022.pdf
- http://home.simula.no/~paalh/students/KennetVuong.pdf
- https://ieeexplore.ieee.org/document/8877406

**Comment by cise-midoglu** [comment]
PmSys screenshots for more insight: https://drive.google.com/drive/folders/15LcBjJn-2z8ZfDgwJcrUHiQ9vvqhfZ4Q?usp=share_link

**Comment by Hens743** [comment]
Done with my last update. Please review.

**Comment by cise-midoglu** [comment]
- [x] Spreadsheet column formatting issue resolve
- [x] Contact GPS vest provider for confirmation of value range, and units

**Comment by cise-midoglu** [comment]
- [x] Forward e-mails to Cise
