### ISSUE TITLE
Create new page: `GPS`

### ISSUE THREAD

**Issue by cise-midoglu** [simulamet-host/soccer-dashboard#23]
- [x] Empty map view

**Comment by Hens743** [comment]
I'm struggling with this creation. It ll take a little more time. I'll ask matthiasboeker some advice

**Comment by cise-midoglu** [comment]
- [x] Add sample data from 3-5 sessions (use 3-5 per player-per session parquet files) in the repository
- [x] Add tabular view of some overview metrics (e.g., number of samples)

| Team | Player | Day | #Samples |
| ------------- | ------------- | ------------- | ------------- | 
| | | | |
| | | | |
| | | | |
| | | | |

**Comment by Hens743** [comment]
Branch updated as talked on 09/12/22. However, the links to the datasets are still based on the 'local' version.  How do you update these links for the online version ?
