### ISSUE TITLE
Automatically add content to `Homepage` from `README.md`

### ISSUE THREAD

**Issue by cise-midoglu** [simulamet-host/soccer-dashboard#32]
(TBU)

**Comment by cise-midoglu** [comment]
Wait for #8 to be merged before creating feature branch from `dev`

**Comment by cise-midoglu** [comment]
Relevant section will be `## How to use the Dashboard`, everything after it should automatically appear in the homepage (but none of the content before)

**Comment by Ismail-De** [comment]
Done. The 'How to use the Dashboard' section does not exist, I selected the 'Soccer Dashboard' section instead.

**Comment by cise-midoglu** [comment]
- [x] @KrishnaSiddharth will look for a way to make this work both locally and in the cloud

**Comment by cise-midoglu** [comment]
When running locally, call the `app.py` from outside the `streamlit_app` folder:

```
streamlit run streamlit_app/app.py
```
