### ISSUE TITLE
Update GPS page (sample analyses)

### ISSUE THREAD

**Issue by cise-midoglu** [simulamet-host/soccer-dashboard#46]
Can still use local data (no dB connection).

- [x] Raw data (tabular view)
- [x] Map visualization
- [x] Analysis
- Number of samples (numeric value)
- Heart rate in time
- Acceleration in time
- Rotation in time

**Comment by Hens743** [comment]
All tasks are done. Some details must be reviewed. Everything works on local repo.

**Comment by cise-midoglu** [comment]
- [x] Screenshots

**Comment by Hens743** [comment]
![Image](https://user-images.githubusercontent.com/80003512/215125056-e4760b18-cf4c-495d-95b7-b2748c04092f.png)



![Image](https://user-images.githubusercontent.com/80003512/215125084-ec52f8b2-b3fb-41f9-a8e4-48cafd28fae8.png)



![Image](https://user-images.githubusercontent.com/80003512/215125201-e51b8095-b994-4f6e-b282-00a1f665add2.png)



![Image](https://user-images.githubusercontent.com/80003512/215125220-c9f8c8f5-c2f6-4205-aa54-7e47aab11850.png)



![Image](https://user-images.githubusercontent.com/80003512/215125233-51b60ec9-d769-4600-9c2d-f64273425c3d.png)



![Image](https://user-images.githubusercontent.com/80003512/215125247-abd2920b-d2d6-48a8-8524-fe9b6300f86f.png)



![Image](https://user-images.githubusercontent.com/80003512/215125265-17579fd2-dd1f-4ef2-935f-7bb0d76e5add.png)



![Image](https://user-images.githubusercontent.com/80003512/215125281-ac5e2688-dbef-4d6b-8c4f-36904c7198d1.png)

**Comment by cise-midoglu** [comment]
- [x] Use the test data in the DB instead of local data

**Comment by cise-midoglu** [comment]
Closed by #59
