### ISSUE TITLE
Import GPS samples to DB

### ISSUE THREAD

**Issue by cise-midoglu** [simulamet-host/soccer-dashboard#48]
Import either from parquet or csv file to the `gps` table (https://www.mysqltutorial.org/import-csv-file-mysql-table/), we don't need too many for the beginning

**Comment by Hens743** [comment]
2 sample of 10 rows from the team A and B have been uploaded in .cvs to the SQL DB.

![Image](https://user-images.githubusercontent.com/80003512/216350162-91ed364a-d216-4d52-8246-371545c971da.png)
