### ISSUE TITLE
Add content to `Homepage`

### ISSUE THREAD

**Issue by cise-midoglu** [simulamet-host/soccer-dashboard#8]
Add dummy content (e.g., a few paragraphs of [Lorem Ipsum](https://www.lipsum.com/)) to the homepage: https://tinyurl.com/soccer-dashboard

**Comment by cise-midoglu** [comment]
Reopening issue as there is a bug in the Streamlit deployment: https://tinyurl.com/soccer-dashboard-internal

Please check if the file `Description.txt` needs to be referred to with an absolute path

![Image](https://user-images.githubusercontent.com/7714406/201462708-c73cfec1-8d5f-4750-a256-cdbd2b5e40b1.png)

**Comment by KrishnaSiddharth** [comment]
Hi Cise. I have made a pull request for this issue. Can you ask Mathias to approve it
